//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.04 at 08:44:41 PM EET 
//


package soap.assignment.lsh.models.soap.emp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bigDecimalMath" type="{http://lsh.assignment.soap/models/soap/emp}bigDecimalMath"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bigDecimalMath"
})
@XmlRootElement(name = "getBigDecimalMathResponse")
public class GetBigDecimalMathResponse {

    @XmlElement(required = true)
    protected BigDecimalMath bigDecimalMath;

    /**
     * Gets the value of the bigDecimalMath property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimalMath }
     *     
     */
    public BigDecimalMath getBigDecimalMath() {
        return bigDecimalMath;
    }

    /**
     * Sets the value of the bigDecimalMath property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimalMath }
     *     
     */
    public void setBigDecimalMath(BigDecimalMath value) {
        this.bigDecimalMath = value;
    }

}
