//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.04 at 08:44:41 PM EET 
//


package soap.assignment.lsh.models.soap.emp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.assignment.lsh.models.soap.emp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.assignment.lsh.models.soap.emp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBigDecimalMathResponse }
     * 
     */
    public GetBigDecimalMathResponse createGetBigDecimalMathResponse() {
        return new GetBigDecimalMathResponse();
    }

    /**
     * Create an instance of {@link BigDecimalMath }
     * 
     */
    public BigDecimalMath createBigDecimalMath() {
        return new BigDecimalMath();
    }

    /**
     * Create an instance of {@link GetBigDecimalMathRequest }
     * 
     */
    public GetBigDecimalMathRequest createGetBigDecimalMathRequest() {
        return new GetBigDecimalMathRequest();
    }

}
